[versions]
kotlin = "2.1.0"
shadow = "9.4.1"
android-gradle = "8.10.0"


[plugins]
# Android
android-application = { id = "com.android.application", version.ref = "android-gradle" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
# Kotlin

kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

# Shadow
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
