// AUTO GENERATED BY JNIGEN 0.15.0. DO NOT EDIT!

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String, bool, double, int;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

/// from: `com.aayush262.dartotsu_extension_bridge.AniyomiExtensionApi`
class AniyomiExtensionApi extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<AniyomiExtensionApi> $type;

  @jni$_.internal
  AniyomiExtensionApi.fromReference(
    jni$_.JReference reference,
  )   : $type = type,
        super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
      r'com/aayush262/dartotsu_extension_bridge/AniyomiExtensionApi');

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<AniyomiExtensionApi?> nullableType =
      $AniyomiExtensionApi$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<AniyomiExtensionApi> type =
      $AniyomiExtensionApi$Type$();
  static final _id_new$ = _class.constructorId(
    r'()V',
  );

  static final _new$ = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>>('globalEnv_NewObject')
      .asFunction<
          jni$_.JniResult Function(
            jni$_.Pointer<jni$_.Void>,
            jni$_.JMethodIDPtr,
          )>();

  /// from: `public void <init>()`
  /// The returned object must be released after use, by calling the [release] method.
  factory AniyomiExtensionApi() {
    return AniyomiExtensionApi.fromReference(
        _new$(_class.reference.pointer, _id_new$ as jni$_.JMethodIDPtr)
            .reference);
  }

  static final _id_initialize = _class.instanceMethodId(
    r'initialize',
    r'(Lcom/aayush262/dartotsu_extension_bridge/aniyomi/CustomMethods;)V',
  );

  static final _initialize = jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JThrowablePtr Function(
                      jni$_.Pointer<jni$_.Void>,
                      jni$_.JMethodIDPtr,
                      jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>)>>(
          'globalEnv_CallVoidMethod')
      .asFunction<
          jni$_.JThrowablePtr Function(jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr, jni$_.Pointer<jni$_.Void>)>();

  /// from: `public fun initialize(customMethods: com.aayush262.dartotsu_extension_bridge.aniyomi.CustomMethods): kotlin.Unit`
  void initialize(
    jni$_.JObject customMethods,
  ) {
    final _$customMethods = customMethods.reference;
    _initialize(reference.pointer, _id_initialize as jni$_.JMethodIDPtr,
            _$customMethods.pointer)
        .check();
  }

  static final _id_initClient = _class.instanceMethodId(
    r'initClient',
    r'(Ljava/util/Map;)V',
  );

  static final _initClient = jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JThrowablePtr Function(
                      jni$_.Pointer<jni$_.Void>,
                      jni$_.JMethodIDPtr,
                      jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>)>>(
          'globalEnv_CallVoidMethod')
      .asFunction<
          jni$_.JThrowablePtr Function(jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr, jni$_.Pointer<jni$_.Void>)>();

  /// from: `public fun initClient(data: kotlin.collections.Map<*, *>): kotlin.Unit`
  void initClient(
    jni$_.JMap<jni$_.JObject?, jni$_.JObject?> map,
  ) {
    final _$map = map.reference;
    _initClient(reference.pointer, _id_initClient as jni$_.JMethodIDPtr,
            _$map.pointer)
        .check();
  }

  static final _id_initializeDesktop = _class.instanceMethodId(
    r'initializeDesktop',
    r'(Ljava/lang/String;)V',
  );

  static final _initializeDesktop = jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JThrowablePtr Function(
                      jni$_.Pointer<jni$_.Void>,
                      jni$_.JMethodIDPtr,
                      jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>)>>(
          'globalEnv_CallVoidMethod')
      .asFunction<
          jni$_.JThrowablePtr Function(jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr, jni$_.Pointer<jni$_.Void>)>();

  /// from: `public fun initializeDesktop(basePath: kotlin.String): kotlin.Unit`
  void initializeDesktop(
    jni$_.JString string,
  ) {
    final _$string = string.reference;
    _initializeDesktop(reference.pointer,
            _id_initializeDesktop as jni$_.JMethodIDPtr, _$string.pointer)
        .check();
  }

  static final _id_getInstalledAnimeExtensions = _class.instanceMethodId(
    r'getInstalledAnimeExtensions',
    r'(Ljava/lang/String;Lkotlin/coroutines/Continuation;)Ljava/lang/Object;',
  );

  static final _getInstalledAnimeExtensions =
      jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JniResult Function(
                      jni$_.Pointer<jni$_.Void>,
                      jni$_.JMethodIDPtr,
                      jni$_.VarArgs<
                          (
                            jni$_.Pointer<jni$_.Void>,
                            jni$_.Pointer<jni$_.Void>
                          )>)>>('globalEnv_CallObjectMethod')
          .asFunction<
              jni$_.JniResult Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.Pointer<jni$_.Void>)>();

  /// from: `public suspend fun getInstalledAnimeExtensions(path: kotlin.String?): kotlin.String`
  /// The returned object must be released after use, by calling the [release] method.
  core$_.Future<jni$_.JString> getInstalledAnimeExtensions(
    jni$_.JString? string,
  ) async {
    final $p = jni$_.ReceivePort();
    final _$continuation = jni$_.ProtectedJniExtensions.newPortContinuation($p);
    final _$string = string?.reference ?? jni$_.jNullReference;
    final $r = _getInstalledAnimeExtensions(
            reference.pointer,
            _id_getInstalledAnimeExtensions as jni$_.JMethodIDPtr,
            _$string.pointer,
            _$continuation.pointer)
        .object<jni$_.JObject>(const jni$_.$JObject$Type$());
    _$continuation.release();
    final jni$_.JObject $o;
    if ($r.isInstanceOf(jni$_.coroutineSingletonsClass)) {
      $r.release();
      final $a = await $p.first;
      $o = jni$_.JObject.fromReference(
          jni$_.JGlobalReference(jni$_.JObjectPtr.fromAddress($a)));
      if ($o.isInstanceOf(jni$_.result$FailureClass)) {
        final $e =
            jni$_.failureExceptionField.get($o, const jni$_.$JObject$Type$());
        $o.release();
        jni$_.Jni.throwException($e.reference.toPointer());
      }
    } else {
      $o = $r;
    }
    return $o.as<jni$_.JString>(
      const jni$_.$JString$Type$(),
      releaseOriginal: true,
    );
  }

  static final _id_getInstalledMangaExtensions = _class.instanceMethodId(
    r'getInstalledMangaExtensions',
    r'(Ljava/lang/String;Lkotlin/coroutines/Continuation;)Ljava/lang/Object;',
  );

  static final _getInstalledMangaExtensions =
      jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JniResult Function(
                      jni$_.Pointer<jni$_.Void>,
                      jni$_.JMethodIDPtr,
                      jni$_.VarArgs<
                          (
                            jni$_.Pointer<jni$_.Void>,
                            jni$_.Pointer<jni$_.Void>
                          )>)>>('globalEnv_CallObjectMethod')
          .asFunction<
              jni$_.JniResult Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.Pointer<jni$_.Void>)>();

  /// from: `public suspend fun getInstalledMangaExtensions(path: kotlin.String?): kotlin.String`
  /// The returned object must be released after use, by calling the [release] method.
  core$_.Future<jni$_.JString> getInstalledMangaExtensions(
    jni$_.JString? string,
  ) async {
    final $p = jni$_.ReceivePort();
    final _$continuation = jni$_.ProtectedJniExtensions.newPortContinuation($p);
    final _$string = string?.reference ?? jni$_.jNullReference;
    final $r = _getInstalledMangaExtensions(
            reference.pointer,
            _id_getInstalledMangaExtensions as jni$_.JMethodIDPtr,
            _$string.pointer,
            _$continuation.pointer)
        .object<jni$_.JObject>(const jni$_.$JObject$Type$());
    _$continuation.release();
    final jni$_.JObject $o;
    if ($r.isInstanceOf(jni$_.coroutineSingletonsClass)) {
      $r.release();
      final $a = await $p.first;
      $o = jni$_.JObject.fromReference(
          jni$_.JGlobalReference(jni$_.JObjectPtr.fromAddress($a)));
      if ($o.isInstanceOf(jni$_.result$FailureClass)) {
        final $e =
            jni$_.failureExceptionField.get($o, const jni$_.$JObject$Type$());
        $o.release();
        jni$_.Jni.throwException($e.reference.toPointer());
      }
    } else {
      $o = $r;
    }
    return $o.as<jni$_.JString>(
      const jni$_.$JString$Type$(),
      releaseOriginal: true,
    );
  }

  static final _id_getPopular = _class.instanceMethodId(
    r'getPopular',
    r'(Ljava/lang/String;ZILkotlin/coroutines/Continuation;)Ljava/lang/Object;',
  );

  static final _getPopular = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<
                      (
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Int32,
                        jni$_.Int32,
                        jni$_.Pointer<jni$_.Void>
                      )>)>>('globalEnv_CallObjectMethod')
      .asFunction<
          jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              int,
              int,
              jni$_.Pointer<jni$_.Void>)>();

  /// from: `public suspend fun getPopular(sourceId: kotlin.String, isAnime: kotlin.Boolean, page: kotlin.Int): kotlin.String`
  /// The returned object must be released after use, by calling the [release] method.
  core$_.Future<jni$_.JString> getPopular(
    jni$_.JString string,
    bool z,
    int i,
  ) async {
    final $p = jni$_.ReceivePort();
    final _$continuation = jni$_.ProtectedJniExtensions.newPortContinuation($p);
    final _$string = string.reference;
    final $r = _getPopular(
            reference.pointer,
            _id_getPopular as jni$_.JMethodIDPtr,
            _$string.pointer,
            z ? 1 : 0,
            i,
            _$continuation.pointer)
        .object<jni$_.JObject>(const jni$_.$JObject$Type$());
    _$continuation.release();
    final jni$_.JObject $o;
    if ($r.isInstanceOf(jni$_.coroutineSingletonsClass)) {
      $r.release();
      final $a = await $p.first;
      $o = jni$_.JObject.fromReference(
          jni$_.JGlobalReference(jni$_.JObjectPtr.fromAddress($a)));
      if ($o.isInstanceOf(jni$_.result$FailureClass)) {
        final $e =
            jni$_.failureExceptionField.get($o, const jni$_.$JObject$Type$());
        $o.release();
        jni$_.Jni.throwException($e.reference.toPointer());
      }
    } else {
      $o = $r;
    }
    return $o.as<jni$_.JString>(
      const jni$_.$JString$Type$(),
      releaseOriginal: true,
    );
  }

  static final _id_getLatestUpdates = _class.instanceMethodId(
    r'getLatestUpdates',
    r'(Ljava/lang/String;ZILkotlin/coroutines/Continuation;)Ljava/lang/Object;',
  );

  static final _getLatestUpdates = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<
                      (
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Int32,
                        jni$_.Int32,
                        jni$_.Pointer<jni$_.Void>
                      )>)>>('globalEnv_CallObjectMethod')
      .asFunction<
          jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              int,
              int,
              jni$_.Pointer<jni$_.Void>)>();

  /// from: `public suspend fun getLatestUpdates(sourceId: kotlin.String, isAnime: kotlin.Boolean, page: kotlin.Int): kotlin.String`
  /// The returned object must be released after use, by calling the [release] method.
  core$_.Future<jni$_.JString> getLatestUpdates(
    jni$_.JString string,
    bool z,
    int i,
  ) async {
    final $p = jni$_.ReceivePort();
    final _$continuation = jni$_.ProtectedJniExtensions.newPortContinuation($p);
    final _$string = string.reference;
    final $r = _getLatestUpdates(
            reference.pointer,
            _id_getLatestUpdates as jni$_.JMethodIDPtr,
            _$string.pointer,
            z ? 1 : 0,
            i,
            _$continuation.pointer)
        .object<jni$_.JObject>(const jni$_.$JObject$Type$());
    _$continuation.release();
    final jni$_.JObject $o;
    if ($r.isInstanceOf(jni$_.coroutineSingletonsClass)) {
      $r.release();
      final $a = await $p.first;
      $o = jni$_.JObject.fromReference(
          jni$_.JGlobalReference(jni$_.JObjectPtr.fromAddress($a)));
      if ($o.isInstanceOf(jni$_.result$FailureClass)) {
        final $e =
            jni$_.failureExceptionField.get($o, const jni$_.$JObject$Type$());
        $o.release();
        jni$_.Jni.throwException($e.reference.toPointer());
      }
    } else {
      $o = $r;
    }
    return $o.as<jni$_.JString>(
      const jni$_.$JString$Type$(),
      releaseOriginal: true,
    );
  }

  static final _id_search = _class.instanceMethodId(
    r'search',
    r'(Ljava/lang/String;ZLjava/lang/String;ILkotlin/coroutines/Continuation;)Ljava/lang/Object;',
  );

  static final _search = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<
                      (
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Int32,
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Int32,
                        jni$_.Pointer<jni$_.Void>
                      )>)>>('globalEnv_CallObjectMethod')
      .asFunction<
          jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              int,
              jni$_.Pointer<jni$_.Void>,
              int,
              jni$_.Pointer<jni$_.Void>)>();

  /// from: `public suspend fun search(sourceId: kotlin.String, isAnime: kotlin.Boolean, query: kotlin.String, page: kotlin.Int): kotlin.String`
  /// The returned object must be released after use, by calling the [release] method.
  core$_.Future<jni$_.JString> search(
    jni$_.JString string,
    bool z,
    jni$_.JString string1,
    int i,
  ) async {
    final $p = jni$_.ReceivePort();
    final _$continuation = jni$_.ProtectedJniExtensions.newPortContinuation($p);
    final _$string = string.reference;
    final _$string1 = string1.reference;
    final $r = _search(
            reference.pointer,
            _id_search as jni$_.JMethodIDPtr,
            _$string.pointer,
            z ? 1 : 0,
            _$string1.pointer,
            i,
            _$continuation.pointer)
        .object<jni$_.JObject>(const jni$_.$JObject$Type$());
    _$continuation.release();
    final jni$_.JObject $o;
    if ($r.isInstanceOf(jni$_.coroutineSingletonsClass)) {
      $r.release();
      final $a = await $p.first;
      $o = jni$_.JObject.fromReference(
          jni$_.JGlobalReference(jni$_.JObjectPtr.fromAddress($a)));
      if ($o.isInstanceOf(jni$_.result$FailureClass)) {
        final $e =
            jni$_.failureExceptionField.get($o, const jni$_.$JObject$Type$());
        $o.release();
        jni$_.Jni.throwException($e.reference.toPointer());
      }
    } else {
      $o = $r;
    }
    return $o.as<jni$_.JString>(
      const jni$_.$JString$Type$(),
      releaseOriginal: true,
    );
  }

  static final _id_getDetail = _class.instanceMethodId(
    r'getDetail',
    r'(Ljava/lang/String;ZLjava/lang/String;Lkotlin/coroutines/Continuation;)Ljava/lang/Object;',
  );

  static final _getDetail = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<
                      (
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Int32,
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>
                      )>)>>('globalEnv_CallObjectMethod')
      .asFunction<
          jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              int,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>)>();

  /// from: `public suspend fun getDetail(sourceId: kotlin.String, isAnime: kotlin.Boolean, media: kotlin.String): kotlin.String`
  /// The returned object must be released after use, by calling the [release] method.
  core$_.Future<jni$_.JString> getDetail(
    jni$_.JString string,
    bool z,
    jni$_.JString string1,
  ) async {
    final $p = jni$_.ReceivePort();
    final _$continuation = jni$_.ProtectedJniExtensions.newPortContinuation($p);
    final _$string = string.reference;
    final _$string1 = string1.reference;
    final $r = _getDetail(
            reference.pointer,
            _id_getDetail as jni$_.JMethodIDPtr,
            _$string.pointer,
            z ? 1 : 0,
            _$string1.pointer,
            _$continuation.pointer)
        .object<jni$_.JObject>(const jni$_.$JObject$Type$());
    _$continuation.release();
    final jni$_.JObject $o;
    if ($r.isInstanceOf(jni$_.coroutineSingletonsClass)) {
      $r.release();
      final $a = await $p.first;
      $o = jni$_.JObject.fromReference(
          jni$_.JGlobalReference(jni$_.JObjectPtr.fromAddress($a)));
      if ($o.isInstanceOf(jni$_.result$FailureClass)) {
        final $e =
            jni$_.failureExceptionField.get($o, const jni$_.$JObject$Type$());
        $o.release();
        jni$_.Jni.throwException($e.reference.toPointer());
      }
    } else {
      $o = $r;
    }
    return $o.as<jni$_.JString>(
      const jni$_.$JString$Type$(),
      releaseOriginal: true,
    );
  }

  static final _id_getVideoList = _class.instanceMethodId(
    r'getVideoList',
    r'(Ljava/lang/String;ZLjava/lang/String;Lkotlin/coroutines/Continuation;)Ljava/lang/Object;',
  );

  static final _getVideoList = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<
                      (
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Int32,
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>
                      )>)>>('globalEnv_CallObjectMethod')
      .asFunction<
          jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              int,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>)>();

  /// from: `public suspend fun getVideoList(sourceId: kotlin.String, isAnime: kotlin.Boolean, episode: kotlin.String): kotlin.String`
  /// The returned object must be released after use, by calling the [release] method.
  core$_.Future<jni$_.JString> getVideoList(
    jni$_.JString string,
    bool z,
    jni$_.JString string1,
  ) async {
    final $p = jni$_.ReceivePort();
    final _$continuation = jni$_.ProtectedJniExtensions.newPortContinuation($p);
    final _$string = string.reference;
    final _$string1 = string1.reference;
    final $r = _getVideoList(
            reference.pointer,
            _id_getVideoList as jni$_.JMethodIDPtr,
            _$string.pointer,
            z ? 1 : 0,
            _$string1.pointer,
            _$continuation.pointer)
        .object<jni$_.JObject>(const jni$_.$JObject$Type$());
    _$continuation.release();
    final jni$_.JObject $o;
    if ($r.isInstanceOf(jni$_.coroutineSingletonsClass)) {
      $r.release();
      final $a = await $p.first;
      $o = jni$_.JObject.fromReference(
          jni$_.JGlobalReference(jni$_.JObjectPtr.fromAddress($a)));
      if ($o.isInstanceOf(jni$_.result$FailureClass)) {
        final $e =
            jni$_.failureExceptionField.get($o, const jni$_.$JObject$Type$());
        $o.release();
        jni$_.Jni.throwException($e.reference.toPointer());
      }
    } else {
      $o = $r;
    }
    return $o.as<jni$_.JString>(
      const jni$_.$JString$Type$(),
      releaseOriginal: true,
    );
  }

  static final _id_getPageList = _class.instanceMethodId(
    r'getPageList',
    r'(Ljava/lang/String;ZLjava/lang/String;Lkotlin/coroutines/Continuation;)Ljava/lang/Object;',
  );

  static final _getPageList = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<
                      (
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Int32,
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>
                      )>)>>('globalEnv_CallObjectMethod')
      .asFunction<
          jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              int,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>)>();

  /// from: `public suspend fun getPageList(sourceId: kotlin.String, isAnime: kotlin.Boolean, episode: kotlin.String): kotlin.String`
  /// The returned object must be released after use, by calling the [release] method.
  core$_.Future<jni$_.JString> getPageList(
    jni$_.JString string,
    bool z,
    jni$_.JString string1,
  ) async {
    final $p = jni$_.ReceivePort();
    final _$continuation = jni$_.ProtectedJniExtensions.newPortContinuation($p);
    final _$string = string.reference;
    final _$string1 = string1.reference;
    final $r = _getPageList(
            reference.pointer,
            _id_getPageList as jni$_.JMethodIDPtr,
            _$string.pointer,
            z ? 1 : 0,
            _$string1.pointer,
            _$continuation.pointer)
        .object<jni$_.JObject>(const jni$_.$JObject$Type$());
    _$continuation.release();
    final jni$_.JObject $o;
    if ($r.isInstanceOf(jni$_.coroutineSingletonsClass)) {
      $r.release();
      final $a = await $p.first;
      $o = jni$_.JObject.fromReference(
          jni$_.JGlobalReference(jni$_.JObjectPtr.fromAddress($a)));
      if ($o.isInstanceOf(jni$_.result$FailureClass)) {
        final $e =
            jni$_.failureExceptionField.get($o, const jni$_.$JObject$Type$());
        $o.release();
        jni$_.Jni.throwException($e.reference.toPointer());
      }
    } else {
      $o = $r;
    }
    return $o.as<jni$_.JString>(
      const jni$_.$JString$Type$(),
      releaseOriginal: true,
    );
  }

  static final _id_getPreferenceScreenMap = _class.instanceMethodId(
    r'getPreferenceScreenMap',
    r'()Ljava/util/Map;',
  );

  static final _getPreferenceScreenMap = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>>('globalEnv_CallObjectMethod')
      .asFunction<
          jni$_.JniResult Function(
            jni$_.Pointer<jni$_.Void>,
            jni$_.JMethodIDPtr,
          )>();

  /// from: `public final java.util.Map<java.lang.String, androidx.preference.PreferenceScreen> getPreferenceScreenMap()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JMap<jni$_.JString, jni$_.JObject> getPreferenceScreenMap() {
    return _getPreferenceScreenMap(
            reference.pointer, _id_getPreferenceScreenMap as jni$_.JMethodIDPtr)
        .object<jni$_.JMap<jni$_.JString, jni$_.JObject>>(
            const jni$_.$JMap$Type$<jni$_.JString, jni$_.JObject>(
                jni$_.$JString$Type$(), jni$_.$JObject$Type$()));
  }

  static final _id_getPreference = _class.instanceMethodId(
    r'getPreference',
    r'(Ljava/lang/String;ZLkotlin/coroutines/Continuation;)Ljava/lang/Object;',
  );

  static final _getPreference = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<
                      (
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Int32,
                        jni$_.Pointer<jni$_.Void>
                      )>)>>('globalEnv_CallObjectMethod')
      .asFunction<
          jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              int,
              jni$_.Pointer<jni$_.Void>)>();

  /// from: `public suspend fun getPreference(sourceId: kotlin.String, isAnime: kotlin.Boolean): kotlin.String`
  /// The returned object must be released after use, by calling the [release] method.
  core$_.Future<jni$_.JString> getPreference(
    jni$_.JString string,
    bool z,
  ) async {
    final $p = jni$_.ReceivePort();
    final _$continuation = jni$_.ProtectedJniExtensions.newPortContinuation($p);
    final _$string = string.reference;
    final $r = _getPreference(
            reference.pointer,
            _id_getPreference as jni$_.JMethodIDPtr,
            _$string.pointer,
            z ? 1 : 0,
            _$continuation.pointer)
        .object<jni$_.JObject>(const jni$_.$JObject$Type$());
    _$continuation.release();
    final jni$_.JObject $o;
    if ($r.isInstanceOf(jni$_.coroutineSingletonsClass)) {
      $r.release();
      final $a = await $p.first;
      $o = jni$_.JObject.fromReference(
          jni$_.JGlobalReference(jni$_.JObjectPtr.fromAddress($a)));
      if ($o.isInstanceOf(jni$_.result$FailureClass)) {
        final $e =
            jni$_.failureExceptionField.get($o, const jni$_.$JObject$Type$());
        $o.release();
        jni$_.Jni.throwException($e.reference.toPointer());
      }
    } else {
      $o = $r;
    }
    return $o.as<jni$_.JString>(
      const jni$_.$JString$Type$(),
      releaseOriginal: true,
    );
  }

  static final _id_saveSourcePreference = _class.instanceMethodId(
    r'saveSourcePreference',
    r'(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lkotlin/coroutines/Continuation;)Ljava/lang/Object;',
  );

  static final _saveSourcePreference = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<
                      (
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>
                      )>)>>('globalEnv_CallObjectMethod')
      .asFunction<
          jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>)>();

  /// from: `public suspend fun saveSourcePreference(sourceId: kotlin.String, key: kotlin.String, value: kotlin.String?): kotlin.Boolean`
  /// The returned object must be released after use, by calling the [release] method.
  core$_.Future<jni$_.JBoolean> saveSourcePreference(
    jni$_.JString string,
    jni$_.JString string1,
    jni$_.JString? string2,
  ) async {
    final $p = jni$_.ReceivePort();
    final _$continuation = jni$_.ProtectedJniExtensions.newPortContinuation($p);
    final _$string = string.reference;
    final _$string1 = string1.reference;
    final _$string2 = string2?.reference ?? jni$_.jNullReference;
    final $r = _saveSourcePreference(
            reference.pointer,
            _id_saveSourcePreference as jni$_.JMethodIDPtr,
            _$string.pointer,
            _$string1.pointer,
            _$string2.pointer,
            _$continuation.pointer)
        .object<jni$_.JObject>(const jni$_.$JObject$Type$());
    _$continuation.release();
    final jni$_.JObject $o;
    if ($r.isInstanceOf(jni$_.coroutineSingletonsClass)) {
      $r.release();
      final $a = await $p.first;
      $o = jni$_.JObject.fromReference(
          jni$_.JGlobalReference(jni$_.JObjectPtr.fromAddress($a)));
      if ($o.isInstanceOf(jni$_.result$FailureClass)) {
        final $e =
            jni$_.failureExceptionField.get($o, const jni$_.$JObject$Type$());
        $o.release();
        jni$_.Jni.throwException($e.reference.toPointer());
      }
    } else {
      $o = $r;
    }
    return $o.as<jni$_.JBoolean>(
      const jni$_.$JBoolean$Type$(),
      releaseOriginal: true,
    );
  }

  static final _id_initializeAndroid = _class.instanceMethodId(
    r'initializeAndroid',
    r'(Ljava/lang/Object;)V',
  );

  static final _initializeAndroid = jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JThrowablePtr Function(
                      jni$_.Pointer<jni$_.Void>,
                      jni$_.JMethodIDPtr,
                      jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>)>>(
          'globalEnv_CallVoidMethod')
      .asFunction<
          jni$_.JThrowablePtr Function(jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr, jni$_.Pointer<jni$_.Void>)>();

  /// from: `public void initializeAndroid(java.lang.Object object)`
  void initializeAndroid(
    jni$_.JObject object,
  ) {
    final _$object = object.reference;
    _initializeAndroid(reference.pointer,
            _id_initializeAndroid as jni$_.JMethodIDPtr, _$object.pointer)
        .check();
  }
}

final class $AniyomiExtensionApi$NullableType$
    extends jni$_.JType<AniyomiExtensionApi?> {
  @jni$_.internal
  const $AniyomiExtensionApi$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lcom/aayush262/dartotsu_extension_bridge/AniyomiExtensionApi;';

  @jni$_.internal
  @core$_.override
  AniyomiExtensionApi? fromReference(jni$_.JReference reference) =>
      reference.isNull
          ? null
          : AniyomiExtensionApi.fromReference(
              reference,
            );
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<AniyomiExtensionApi?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($AniyomiExtensionApi$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($AniyomiExtensionApi$NullableType$) &&
        other is $AniyomiExtensionApi$NullableType$;
  }
}

final class $AniyomiExtensionApi$Type$
    extends jni$_.JType<AniyomiExtensionApi> {
  @jni$_.internal
  const $AniyomiExtensionApi$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lcom/aayush262/dartotsu_extension_bridge/AniyomiExtensionApi;';

  @jni$_.internal
  @core$_.override
  AniyomiExtensionApi fromReference(jni$_.JReference reference) =>
      AniyomiExtensionApi.fromReference(
        reference,
      );
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<AniyomiExtensionApi?> get nullableType =>
      const $AniyomiExtensionApi$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($AniyomiExtensionApi$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($AniyomiExtensionApi$Type$) &&
        other is $AniyomiExtensionApi$Type$;
  }
}
